server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: inventory-service
          uri: lb://inventory-service
          predicates:
            - Path=/inventory/**
        - id: consignment-service
          uri: lb://consignment-service
          predicates:
            - Path=/consignment/**
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
        - id: email-service
          uri: lb://email-service
          predicates:
            - Path=/email/**
        - id: batch-job-service
          uri: lb://batch-job-service
          predicates:
            - Path=/batch/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
